name = "markirovka"
compatibility_date = "2024-09-23"
main = "worker.js"
preview_urls = true

[assets]
# Directory with the static build output produced by `npm run build`
directory = "dist"
# Binding name used in the worker.js fetch handler
binding = "ASSETS"

# R2 Storage binding for secure file uploads via Worker
[[r2_buckets]]
binding = "R2"
bucket_name = "markirovka-storage"

# Environment variables (secrets should be set via: wrangler secret put VARIABLE_NAME)
# These can be set in Cloudflare Dashboard or via CLI:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# Or add them to .dev.vars for local development
